kind: Pod
apiVersion: v1
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  containers:
    - name: kibana
      image: docker.elastic.co/kibana/kibana:7.6.0
      env:
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch
              key: password
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        - name: XPACK_SECURITY_ENABLED
          value: "true"
      ports:
        - containerPort: 5601
          name: http
          protocol: TCP
