kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticserach-pv
  labels:
    app: elasticserach-pv
spec:
  storageClassName: aws-gp2
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-XXXX
    fsType: ext4
