apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
  labels:
    app: elasticserach-pvc
spec:
  storageClassName: aws-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      app: elasticserach-pv
