apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-config
data:
  elasticsearch.yml: |
        cluster.name: "CLUSTERNAME"
        network.host: 0.0.0.0
        xpack.license.self_generated.type: trial
        xpack.security.enabled: true
        xpack.monitoring.collection.enabled: true
